version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=enfuse
      - POSTGRES_PASSWORD=enfuse-internal
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
